services:
  llm-bot-1:
    command: -m /models/llm/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf -c 4096 --host
      0.0.0.0 --port 8080
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            count: all
            driver: nvidia
    image: ghcr.io/ggml-org/llama.cpp:server-vulkan
  llm-bot-2:
    command: -m /models/llm/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf -c 4096 --host
      0.0.0.0 --port 8080
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            count: all
            driver: nvidia
    image: ghcr.io/ggml-org/llama.cpp:server-vulkan
  llm-bot-3:
    command: -m /models/llm/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf -c 4096 --host
      0.0.0.0 --port 8080
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            count: all
            driver: nvidia
    image: ghcr.io/ggml-org/llama.cpp:server-vulkan
  llm-god:
    command: -m /models/llm/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf -c 4096 --host
      0.0.0.0 --port 8080
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            count: all
            driver: nvidia
    image: ghcr.io/ggml-org/llama.cpp:server-vulkan
  llm-main:
    command: -m /models/llm/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf -c 4096 --host
      0.0.0.0 --port 8080
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            count: all
            driver: nvidia
    image: ghcr.io/ggml-org/llama.cpp:server-vulkan
version: '3.8'
